dalkoscout:
  image: d4lk0s/dalkoscout
  environment:
    TZ: America/New_York
    MONGO_CONNECTION: mongodb://mongo:27017/nightscout
    # Require Password (API_SECRET) in Dalkoscout Portal
    AUTH_DEFAULT_ROLES: denied
    API_SECRET: dalkoscout
    # Blood Glucose Settings
    BG_HIGH: 220
    BG_LOW: 60
    BG_TARGET_TOP: 160
    BG_TARGET_BOTTOM: 80
    # Sensor Age Alert
    SAGE_ENABLE_ALERTS: true
    # Enable all NightScout Apps (including IFTTT and Amazon Echo)
    ENABLE: careportal boluscalc food rawbg iob cob bwp cage sage iage basal maker alexa
    # Enable IFTTT Maker (interact with your SmartHome lights, etc.)
    MAKER_KEY: xxxxxxxxxxxxxxxxxxxxx
    # SSL Settings
    SSL_KEY: /var/opt/ssl/privkey.pem
    SSL_CERT: /var/opt/ssl/fullchain.pem
  ports:
    - "1337:1337"
  links:
    - mongo
  volumes:
    - /home/pi/docker/dalkoscout:/var/opt/ssl/:ro
  restart: unless-stopped
mongo:
  build: ./dalkoscout-mongo
  command: "./mongod-start.sh"
  restart: unless-stopped
